/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class Environment_LibC */

#ifndef _Included_EnvironmentLib_
#define _Included_EnvironmentLib_
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     EnvironmentLib
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_EnvironmentLib_setenv
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     EnvironmentLib
 * Method:    unsetenv
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_EnvironmentLib_unsetenv
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
