on: [push]

jobs:

  compile-linux:
    name: Compile on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: g++ -shared -fPIC -o libnativeEnv.so EnvironmentLib.o -lc

  compile-windows:
    name: Compile on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: g++ -shared -o nativeEnv.dll EnvironmentLib.o -Wl,--add-stdcall-alias


  compile-macos:
    name: compile on macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: g++ -dynamiclib -o libnativeEnv.dylib EnvironmentLib.o -lc
